### ISSUE TITLE
build.yaml removed while applying cookiecutter

### ISSUE THREAD

**Issue by 8bitsam** [diffpy/diffpy.pdffit2#48]
This is for reference. Here is the old build.yaml code:
```
name: build and upload

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Check-out repository
      uses: actions/checkout@v2

    - name: set up conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        conda install -c conda-forge twine
        conda install -c conda-forge wheel
        conda install -c conda-forge setuptools
        conda install -c conda-forge pip
        conda install -c conda-forge gsl

    - name: Build wheels
      run: |
        python setup.py sdist bdist_wheel

    - name: Run tests
      run: |
        conda install -c conda-forge numpy
        python setup.py install
        python conda-recipe/run_test.py

    - name: Upload Artifacts GitHub releases
      uses: ncipollo/release-action@v1
      with:
        draft: false
        prerelease: true
        allowUpdates: true
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ github.workspace }}/dist/*.whl
        tag: 1.4.1
        body: This is an alpha build of the pdffit2 library (1.4.2)

    # This step will upload tagged commits to pypi.
    # The pypi token must be added to GH secrets
    #
    # - name: Publish package
    #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     password: ${{ secrets.PYPI_API_TOKEN }}
```
